const blogEditorTheme = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "blog-editor-placeholder",
  paragraph: "blog-editor-paragraph",
  quote: "blog-editor-quote",
  heading: {
    h1: "blog-editor-h1",
    h2: "blog-editor-h2",
    h3: "blog-editor-h3",
    h4: "blog-editor-h4",
    h5: "blog-editor-h5",
  },
  list: {
    nested: {
      listitem: "blog-editor-nested-listitem",
    },
    ol: "blog-editor-ol",
    ul: "blog-editor-ul",
    listitem: "blog-editor-listitem",
  },
  image: "blog-editor-image",
  link: "blog-editor-link",
  text: {
    bold: "blog-editor-text-bold",
    italic: "blog-editor-text-italic",
    overflowed: "blog-editor-text-overflowed",
    hashtag: "blog-editor-text-hashtag",
    underline: "blog-editor-text-underline",
    strikethrough: "blog-editor-text-strikethrough",
    underlineStrikethrough: "blog-editor-text-underlineStrikethrough",
    code: "blog-editor-text-code",
  },
  code: "blog-editor-code",
  codeHighlight: {
    atrule: "blog-editor-tokenAttr",
    attr: "blog-editor-tokenAttr",
    boolean: "blog-editor-tokenProperty",
    builtin: "blog-editor-tokenSelector",
    cdata: "blog-editor-tokenComment",
    char: "blog-editor-tokenSelector",
    class: "blog-editor-tokenFunction",
    "class-name": "blog-editor-tokenFunction",
    comment: "blog-editor-tokenComment",
    constant: "blog-editor-tokenProperty",
    deleted: "blog-editor-tokenProperty",
    doctype: "blog-editor-tokenComment",
    entity: "blog-editor-tokenOperator",
    function: "blog-editor-tokenFunction",
    important: "blog-editor-tokenVariable",
    inserted: "blog-editor-tokenSelector",
    keyword: "blog-editor-tokenAttr",
    namespace: "blog-editor-tokenVariable",
    number: "blog-editor-tokenProperty",
    operator: "blog-editor-tokenOperator",
    prolog: "blog-editor-tokenComment",
    property: "blog-editor-tokenProperty",
    punctuation: "blog-editor-tokenPunctuation",
    regex: "blog-editor-tokenVariable",
    selector: "blog-editor-tokenSelector",
    string: "blog-editor-tokenSelector",
    symbol: "blog-editor-tokenProperty",
    tag: "blog-editor-tokenProperty",
    url: "blog-editor-tokenOperator",
    variable: "blog-editor-tokenVariable",
  },
  table: "blog-editor-table",
  tableAddRows: "blog-editor-tableAddRows",
  tableCell: "blog-editor-tableCell",
  tableCellActionButton: "blog-editor-tableCellActionButton",
  tableCellActionButtonContainer: "blog-editor-tableCellActionButtonContainer",
  tableCellEditing: "blog-editor-tableCellEditing",
  tableRow: "blog-editor-tableRow",
  tableSelection: "blog-editor-tableSelection",
};

export default blogEditorTheme;
